#!/bin/sh

echo "Docker set up on $KAMAL_HOSTS..."
bin/kamal proxy boot_config set --registry ccr.ccs.tencentyun.com --repository kamal --image_version v0.9.1 -d $KAMAL_DESTINATION
bin/kamal server exec 'mkdir emqx_data && chmod o+w ~/emqx_data' -d $KAMAL_DESTINATION

exit 0
