#!/bin/sh

rake assets:precompile
cp .gitmodules.deploy .gitmodules

if [ -n "$(git status public/assets --porcelain)" ]; then
  git add public/assets
  git add .gitmodules
  git commit -m 'update assets'
fi

exit 0
