class RemoveProdMigrate1 < ActiveRecord::Migration[8.2]

  def change
    drop_table :action_mailbox_inbound_emails if table_exists? :action_mailbox_inbound_emails
    drop_table :action_text_rich_texts if table_exists? :action_text_rich_texts
    drop_table :active_storage_attachments if table_exists? :active_storage_attachments
    drop_table :active_storage_blobs if table_exists? :active_storage_blobs
    drop_table :active_storage_variant_records if table_exists? :active_storage_variant_records
    drop_table :alipay_apps if table_exists? :alipay_apps
    drop_table :attend_absence_stats if table_exists? :attend_absence_stats
    drop_table :attend_absences if table_exists? :attend_absences
    drop_table :attend_attendance_logs if table_exists? :attend_attendance_logs
    drop_table :attend_attendance_settings if table_exists? :attend_attendance_settings
    drop_table :attend_attendance_stats if table_exists? :attend_attendance_stats
    drop_table :attend_attendances if table_exists? :attend_attendances
    drop_table :attend_extra_days if table_exists? :attend_extra_days
    drop_table :attend_financial_months if table_exists? :attend_financial_months
    drop_table :attend_overtimes if table_exists? :attend_overtimes
    drop_table :auditor_approvals if table_exists? :auditor_approvals
    drop_table :auditor_audits if table_exists? :auditor_audits
    drop_table :auditor_verifications if table_exists? :auditor_verifications
    drop_table :auditor_verifiers if table_exists? :auditor_verifiers
    drop_table :auth_apps if table_exists? :auth_apps
    drop_table :auth_oauth_users if table_exists? :auth_oauth_users
    drop_table :auth_sessions if table_exists? :auth_sessions
    drop_table :auth_user_taggeds if table_exists? :auth_user_taggeds
    drop_table :auth_user_tags if table_exists? :auth_user_tags
    drop_table :org_supports if table_exists? :org_supports
    drop_table :auth_users if table_exists? :auth_users
    drop_table :auth_verify_tokens if table_exists? :auth_verify_tokens
    drop_table :bench_facilitate_indicators if table_exists? :bench_facilitate_indicators
    drop_table :bench_facilitate_providers if table_exists? :bench_facilitate_providers
    drop_table :bench_facilitate_taxon_hierarchies if table_exists? :bench_facilitate_taxon_hierarchies
    drop_table :bench_facilitate_taxons if table_exists? :bench_facilitate_taxons
    drop_table :bench_facilitates if table_exists? :bench_facilitates
    drop_table :bench_facilitatings if table_exists? :bench_facilitatings
    drop_table :bench_facilitators if table_exists? :bench_facilitators
    drop_table :bench_indicators if table_exists? :bench_indicators
    drop_table :bench_mileposts if table_exists? :bench_mileposts
    drop_table :bench_project_facilitates if table_exists? :bench_project_facilitates
    drop_table :bench_project_indicators if table_exists? :bench_project_indicators
    drop_table :bench_project_mileposts if table_exists? :bench_project_mileposts
    drop_table :bench_project_stages if table_exists? :bench_project_stages
    drop_table :bench_project_webhooks if table_exists? :bench_project_webhooks
    drop_table :bench_projects if table_exists? :bench_projects
    drop_table :bench_standard_providers if table_exists? :bench_standard_providers
    drop_table :bench_standards if table_exists? :bench_standards
    drop_table :bench_task_hierarchies if table_exists? :bench_task_hierarchies
    drop_table :bench_task_template_hierarchies if table_exists? :bench_task_template_hierarchies
    drop_table :bench_task_templates if table_exists? :bench_task_templates
    drop_table :bench_task_timers if table_exists? :bench_task_timers
    drop_table :bench_tasks if table_exists? :bench_tasks
    drop_table :bench_taxon_facilitates if table_exists? :bench_taxon_facilitates
    drop_table :bench_taxon_indicators if table_exists? :bench_taxon_indicators
    drop_table :bench_taxons if table_exists? :bench_taxons
    drop_table :cms_audio_tags if table_exists? :cms_audio_tags
    drop_table :cms_audios if table_exists? :cms_audios
    drop_table :cms_carousels if table_exists? :cms_carousels
    drop_table :cms_catalogs if table_exists? :cms_catalogs
    drop_table :cms_covers if table_exists? :cms_covers
    drop_table :cms_posts if table_exists? :cms_posts
    drop_table :cms_progressions if table_exists? :cms_progressions
    drop_table :cms_tags if table_exists? :cms_tags
    drop_table :cms_videos if table_exists? :cms_videos
    drop_table :com_acme_accounts if table_exists? :com_acme_accounts
    drop_table :com_acme_domains if table_exists? :com_acme_domains
    drop_table :com_acme_identifiers if table_exists? :com_acme_identifiers
    drop_table :com_acme_orders if table_exists? :com_acme_orders
    drop_table :com_acme_servicers if table_exists? :com_acme_servicers
    drop_table :com_blob_defaults if table_exists? :com_blob_defaults
    drop_table :com_blob_pdfs if table_exists? :com_blob_pdfs
    drop_table :com_blob_temps if table_exists? :com_blob_temps
    drop_table :com_cache_lists if table_exists? :com_cache_lists
    drop_table :com_csps if table_exists? :com_csps
    drop_table :com_detector_bots if table_exists? :com_detector_bots
    drop_table :com_detector_logs if table_exists? :com_detector_logs
    drop_table :com_detectors if table_exists? :com_detectors
    drop_table :com_err_bots if table_exists? :com_err_bots
    drop_table :com_err_notices if table_exists? :com_err_notices
    drop_table :com_err_summaries if table_exists? :com_err_summaries
    drop_table :com_errs if table_exists? :com_errs
    drop_table :com_filter_columns if table_exists? :com_filter_columns
    drop_table :com_filters if table_exists? :com_filters
    drop_table :com_infos if table_exists? :com_infos
    drop_table :com_ssh_keys if table_exists? :com_ssh_keys
    drop_table :com_state_hierarchies if table_exists? :com_state_hierarchies
    drop_table :com_states if table_exists? :com_states
    drop_table :crm_agencies if table_exists? :crm_agencies
    drop_table :crm_client_hierarchies if table_exists? :crm_client_hierarchies
    drop_table :crm_clients if table_exists? :crm_clients
    drop_table :crm_contacts if table_exists? :crm_contacts
    drop_table :org_tutorials if table_exists? :org_tutorials
    drop_table :crm_maintain_sources if table_exists? :crm_maintain_sources
    drop_table :crm_maintain_tags if table_exists? :crm_maintain_tags
    drop_table :crm_maintains if table_exists? :crm_maintains
    drop_table :crm_notes if table_exists? :crm_notes
    drop_table :crm_qrcodes if table_exists? :crm_qrcodes
    drop_table :crm_source_contacts if table_exists? :crm_source_contacts
    drop_table :crm_source_hierarchies if table_exists? :crm_source_hierarchies
    drop_table :crm_sources if table_exists? :crm_sources
    drop_table :crm_tags if table_exists? :crm_tags
    drop_table :crm_texts if table_exists? :crm_texts
    drop_table :datum_data_lists if table_exists? :datum_data_lists
    drop_table :datum_export_items if table_exists? :datum_export_items
    drop_table :datum_exports if table_exists? :datum_exports
    drop_table :datum_record_lists if table_exists? :datum_record_lists
    drop_table :datum_table_items if table_exists? :datum_table_items
    drop_table :datum_table_lists if table_exists? :datum_table_lists
    drop_table :datum_template_items if table_exists? :datum_template_items
    drop_table :datum_templates if table_exists? :datum_templates
    drop_table :datum_validations if table_exists? :datum_validations
    drop_table :debug_manies if table_exists? :debug_manies
    drop_table :debug_muches if table_exists? :debug_muches
    drop_table :debug_ones if table_exists? :debug_ones
    drop_table :debug_throughs if table_exists? :debug_throughs
    drop_table :detail_contents if table_exists? :detail_contents
    drop_table :detail_entity_items if table_exists? :detail_entity_items
    drop_table :detail_items if table_exists? :detail_items
    drop_table :detail_knowings if table_exists? :detail_knowings
    drop_table :detail_knowledge_hierarchies if table_exists? :detail_knowledge_hierarchies
    drop_table :detail_knowledges if table_exists? :detail_knowledges
    drop_table :detail_lists if table_exists? :detail_lists
    drop_table :detail_post_syncs if table_exists? :detail_post_syncs
    drop_table :detail_posts if table_exists? :detail_posts
    drop_table :detail_taxon_items if table_exists? :detail_taxon_items
    drop_table :douyin_apps if table_exists? :douyin_apps
    drop_table :douyin_orders if table_exists? :douyin_orders
    drop_table :douyin_shops if table_exists? :douyin_shops
    drop_table :email_logs if table_exists? :email_logs
    drop_table :email_reasons if table_exists? :email_reasons
    drop_table :email_smtp_accounts if table_exists? :email_smtp_accounts
    drop_table :email_smtps if table_exists? :email_smtps
    drop_table :email_subscriptions if table_exists? :email_subscriptions
    drop_table :email_templates if table_exists? :email_templates
    drop_table :eventual_bookings if table_exists? :eventual_bookings
    drop_table :eventual_crowd_members if table_exists? :eventual_crowd_members
    drop_table :eventual_crowds if table_exists? :eventual_crowds
    drop_table :eventual_event_crowds if table_exists? :eventual_event_crowds
    drop_table :eventual_event_grants if table_exists? :eventual_event_grants
    drop_table :eventual_event_items if table_exists? :eventual_event_items
    drop_table :eventual_event_joins if table_exists? :eventual_event_joins
    drop_table :eventual_event_taxons if table_exists? :eventual_event_taxons
    drop_table :eventual_events if table_exists? :eventual_events
    drop_table :eventual_halls if table_exists? :eventual_halls
    drop_table :eventual_place_taxon_hierarchies if table_exists? :eventual_place_taxon_hierarchies
    drop_table :eventual_place_taxons if table_exists? :eventual_place_taxons
    drop_table :eventual_places if table_exists? :eventual_places
    drop_table :eventual_plan_attenders if table_exists? :eventual_plan_attenders
    drop_table :print_bluetooth_printers if table_exists? :print_bluetooth_printers
    drop_table :eventual_seats if table_exists? :eventual_seats
    drop_table :eventual_time_items if table_exists? :eventual_time_items
    drop_table :eventual_time_lists if table_exists? :eventual_time_lists
    drop_table :eventual_plans if table_exists? :eventual_plans
    drop_table :factory_barcodes if table_exists? :factory_barcodes
    drop_table :factory_brands if table_exists? :factory_brands
    drop_table :factory_component_parts if table_exists? :factory_component_parts
    drop_table :factory_components if table_exists? :factory_components
    drop_table :factory_factory_providers if table_exists? :factory_factory_providers
    drop_table :factory_factory_taxons if table_exists? :factory_factory_taxons
    drop_table :factory_fits if table_exists? :factory_fits
    drop_table :factory_part_plans if table_exists? :factory_part_plans
    drop_table :factory_produce_plans if table_exists? :factory_produce_plans
    drop_table :factory_produces if table_exists? :factory_produces
    drop_table :factory_product_produces if table_exists? :factory_product_produces
    drop_table :factory_production_carts if table_exists? :factory_production_carts
    drop_table :factory_production_items if table_exists? :factory_production_items
    drop_table :factory_production_parts if table_exists? :factory_production_parts
    drop_table :factory_production_plans if table_exists? :factory_production_plans
    drop_table :factory_production_provides if table_exists? :factory_production_provides
    drop_table :factory_production_spaces if table_exists? :factory_production_spaces
    drop_table :factory_productions if table_exists? :factory_productions
    drop_table :factory_products if table_exists? :factory_products
    drop_table :factory_scene_automatics if table_exists? :factory_scene_automatics
    drop_table :factory_scenes if table_exists? :factory_scenes
    drop_table :factory_serial_hierarchies if table_exists? :factory_serial_hierarchies
    drop_table :factory_serials if table_exists? :factory_serials
    drop_table :factory_stock_logs if table_exists? :factory_stock_logs
    drop_table :factory_taxon_hierarchies if table_exists? :factory_taxon_hierarchies
    drop_table :factory_taxon_provides if table_exists? :factory_taxon_provides
    drop_table :factory_taxons if table_exists? :factory_taxons
    drop_table :factory_unifiers if table_exists? :factory_unifiers
    drop_table :finance_assessments if table_exists? :finance_assessments
    drop_table :finance_budgets if table_exists? :finance_budgets
    drop_table :finance_expense_items if table_exists? :finance_expense_items
    drop_table :finance_expense_members if table_exists? :finance_expense_members
    drop_table :finance_expenses if table_exists? :finance_expenses
    drop_table :finance_fund_incomes if table_exists? :finance_fund_incomes
    drop_table :finance_funds if table_exists? :finance_funds
    drop_table :finance_stocks if table_exists? :finance_stocks
    drop_table :finance_taxon_hierarchies if table_exists? :finance_taxon_hierarchies
    drop_table :finance_taxons if table_exists? :finance_taxons
    drop_table :growth_aim_codes if table_exists? :growth_aim_codes
    drop_table :growth_aim_entities if table_exists? :growth_aim_entities
    drop_table :growth_aim_logs if table_exists? :growth_aim_logs
    drop_table :growth_aim_users if table_exists? :growth_aim_users
    drop_table :growth_aims if table_exists? :growth_aims
    drop_table :growth_praise_incomes if table_exists? :growth_praise_incomes
    drop_table :growth_praise_users if table_exists? :growth_praise_users
    drop_table :print_devices if table_exists? :print_devices
    drop_table :growth_reward_expenses if table_exists? :growth_reward_expenses
    drop_table :growth_reward_incomes if table_exists? :growth_reward_incomes
    drop_table :growth_rewards if table_exists? :growth_rewards
    drop_table :interact_abuses if table_exists? :interact_abuses
    drop_table :interact_attitudes if table_exists? :interact_attitudes
    drop_table :interact_comments if table_exists? :interact_comments
    drop_table :interact_stars if table_exists? :interact_stars
    drop_table :log_queries if table_exists? :log_queries
    drop_table :log_query_dailies if table_exists? :log_query_dailies
    drop_table :log_request_dailies if table_exists? :log_request_dailies
    drop_table :log_request_weeklies if table_exists? :log_request_weeklies
    drop_table :log_requests if table_exists? :log_requests
    drop_table :log_summary_dailies if table_exists? :log_summary_dailies
    drop_table :markdown_assets if table_exists? :markdown_assets
    drop_table :markdown_catalogs if table_exists? :markdown_catalogs
    drop_table :markdown_github_apps if table_exists? :markdown_github_apps
    drop_table :markdown_gits if table_exists? :markdown_gits
    drop_table :markdown_posts if table_exists? :markdown_posts
    drop_table :notice_announcement_departments if table_exists? :notice_announcement_departments
    drop_table :notice_announcement_job_titles if table_exists? :notice_announcement_job_titles
    drop_table :notice_announcement_organs if table_exists? :notice_announcement_organs
    drop_table :notice_announcement_user_tags if table_exists? :notice_announcement_user_tags
    drop_table :notice_announcements if table_exists? :notice_announcements
    drop_table :notice_notification_sendings if table_exists? :notice_notification_sendings
    drop_table :notice_notifications if table_exists? :notice_notifications
    drop_table :one_ai_app_models if table_exists? :one_ai_app_models
    drop_table :one_ai_apps if table_exists? :one_ai_apps
    drop_table :one_ai_chats if table_exists? :one_ai_chats
    drop_table :one_ai_messages if table_exists? :one_ai_messages
    drop_table :one_ai_system_apps if table_exists? :one_ai_system_apps
    drop_table :one_ai_systems if table_exists? :one_ai_systems
    drop_table :org_department_grants if table_exists? :org_department_grants
    drop_table :org_department_hierarchies if table_exists? :org_department_hierarchies
    drop_table :org_departments if table_exists? :org_departments
    drop_table :org_job_titles if table_exists? :org_job_titles
    drop_table :org_job_transfers if table_exists? :org_job_transfers
    drop_table :print_errs if table_exists? :print_errs
    drop_table :org_member_departments if table_exists? :org_member_departments
    drop_table :org_members if table_exists? :org_members
    drop_table :org_organ_domains if table_exists? :org_organ_domains
    drop_table :org_organ_handles if table_exists? :org_organ_handles
    drop_table :org_organ_hierarchies if table_exists? :org_organ_hierarchies
    drop_table :org_resign_reasons if table_exists? :org_resign_reasons
    drop_table :org_resign_references if table_exists? :org_resign_references
    drop_table :org_organs if table_exists? :org_organs
    drop_table :org_resigns if table_exists? :org_resigns
    drop_table :org_shortcuts if table_exists? :org_shortcuts
    drop_table :org_super_job_titles if table_exists? :org_super_job_titles
    drop_table :print_jia_bo_apps if table_exists? :print_jia_bo_apps
    drop_table :print_jia_bo_printers if table_exists? :print_jia_bo_printers
    drop_table :print_mqtt_apps if table_exists? :print_mqtt_apps
    drop_table :print_template_items if table_exists? :print_template_items
    drop_table :print_templates if table_exists? :print_templates
    drop_table :roled_cache_roles if table_exists? :roled_cache_roles
    drop_table :roled_caches if table_exists? :roled_caches
    drop_table :roled_role_rules if table_exists? :roled_role_rules
    drop_table :roled_role_types if table_exists? :roled_role_types
    drop_table :roled_role_whos if table_exists? :roled_role_whos
    drop_table :roled_roles if table_exists? :roled_roles
    drop_table :roled_tabs if table_exists? :roled_tabs
    drop_table :ship_address_uses if table_exists? :ship_address_uses
    drop_table :ship_area_hierarchies if table_exists? :ship_area_hierarchies
    drop_table :ship_addresses if table_exists? :ship_addresses
    drop_table :ship_box_holds if table_exists? :ship_box_holds
    drop_table :ship_areas if table_exists? :ship_areas
    drop_table :ship_box_hosts if table_exists? :ship_box_hosts
    drop_table :ship_box_logs if table_exists? :ship_box_logs
    drop_table :ship_box_proxy_buys if table_exists? :ship_box_proxy_buys
    drop_table :ship_box_proxy_sells if table_exists? :ship_box_proxy_sells
    drop_table :ship_box_sells if table_exists? :ship_box_sells
    drop_table :ship_box_specifications if table_exists? :ship_box_specifications
    drop_table :ship_boxes if table_exists? :ship_boxes
    drop_table :ship_car_drivers if table_exists? :ship_car_drivers
    drop_table :ship_cars if table_exists? :ship_cars
    drop_table :ship_drivers if table_exists? :ship_drivers
    drop_table :ship_favorites if table_exists? :ship_favorites
    drop_table :ship_ips if table_exists? :ship_ips
    drop_table :ship_line_similars if table_exists? :ship_line_similars
    drop_table :ship_line_stations if table_exists? :ship_line_stations
    drop_table :ship_lines if table_exists? :ship_lines
    drop_table :ship_locations if table_exists? :ship_locations
    drop_table :ship_shipment_items if table_exists? :ship_shipment_items
    drop_table :ship_shipment_logs if table_exists? :ship_shipment_logs
    drop_table :ship_shipments if table_exists? :ship_shipments
    drop_table :ship_ways if table_exists? :ship_ways
    drop_table :space_buildings if table_exists? :space_buildings
    drop_table :space_desks if table_exists? :space_desks
    drop_table :space_grids if table_exists? :space_grids
    drop_table :space_rooms if table_exists? :space_rooms
    drop_table :space_stations if table_exists? :space_stations
    drop_table :sync_apps if table_exists? :sync_apps
    drop_table :sync_audits if table_exists? :sync_audits
    drop_table :sync_form_hierarchies if table_exists? :sync_form_hierarchies
    drop_table :sync_forms if table_exists? :sync_forms
    drop_table :sync_items if table_exists? :sync_items
    drop_table :sync_logs if table_exists? :sync_logs
    drop_table :sync_records if table_exists? :sync_records
    drop_table :trade_addition_charges if table_exists? :trade_addition_charges
    drop_table :trade_additions if table_exists? :trade_additions
    drop_table :trade_card_prepayments if table_exists? :trade_card_prepayments
    drop_table :trade_card_purchases if table_exists? :trade_card_purchases
    drop_table :trade_card_templates if table_exists? :trade_card_templates
    drop_table :trade_cards if table_exists? :trade_cards
    drop_table :trade_advances if table_exists? :trade_advances
    drop_table :trade_cart_promotes if table_exists? :trade_cart_promotes
    drop_table :trade_carts if table_exists? :trade_carts
    drop_table :trade_deliveries if table_exists? :trade_deliveries
    drop_table :trade_exchange_rates if table_exists? :trade_exchange_rates
    drop_table :trade_holds if table_exists? :trade_holds
    drop_table :trade_item_promotes if table_exists? :trade_item_promotes
    drop_table :trade_items if table_exists? :trade_items
    drop_table :trade_orders if table_exists? :trade_orders
    drop_table :trade_payment_methods if table_exists? :trade_payment_methods
    drop_table :trade_payment_references if table_exists? :trade_payment_references
    drop_table :trade_payment_strategies if table_exists? :trade_payment_strategies
    drop_table :trade_payments if table_exists? :trade_payments
    drop_table :trade_payouts if table_exists? :trade_payouts
    drop_table :trade_privileges if table_exists? :trade_privileges
    drop_table :trade_promote_charges if table_exists? :trade_promote_charges
    drop_table :trade_promote_extras if table_exists? :trade_promote_extras
    drop_table :trade_promote_goods if table_exists? :trade_promote_goods
    drop_table :trade_promotes if table_exists? :trade_promotes
    drop_table :trade_purchases if table_exists? :trade_purchases
    drop_table :trade_refund_orders if table_exists? :trade_refund_orders
    drop_table :trade_refunds if table_exists? :trade_refunds
    drop_table :trade_rent_charges if table_exists? :trade_rent_charges
    drop_table :trade_units if table_exists? :trade_units
    drop_table :trade_wallet_sells if table_exists? :trade_wallet_sells
    drop_table :trade_wallet_frozens if table_exists? :trade_wallet_frozens
    drop_table :wechat_auths if table_exists? :wechat_auths
    drop_table :wechat_categories if table_exists? :wechat_categories
    drop_table :wechat_category_hierarchies if table_exists? :wechat_category_hierarchies
    drop_table :wechat_contacts if table_exists? :wechat_contacts
    drop_table :wechat_apps if table_exists? :wechat_apps
    drop_table :wechat_corp_external_users if table_exists? :wechat_corp_external_users
    drop_table :wechat_corp_users if table_exists? :wechat_corp_users
    drop_table :wechat_corps if table_exists? :wechat_corps
    drop_table :wechat_extractions if table_exists? :wechat_extractions
    drop_table :wechat_extractors if table_exists? :wechat_extractors
    drop_table :wechat_hooks if table_exists? :wechat_hooks
    drop_table :wechat_medias if table_exists? :wechat_medias
    drop_table :wechat_menu_apps if table_exists? :wechat_menu_apps
    drop_table :wechat_menu_disables if table_exists? :wechat_menu_disables
    drop_table :wechat_menu_root_apps if table_exists? :wechat_menu_root_apps
    drop_table :wechat_menu_roots if table_exists? :wechat_menu_roots
    drop_table :wechat_menus if table_exists? :wechat_menus
    drop_table :wechat_messages if table_exists? :wechat_messages
    drop_table :wechat_news_reply_items if table_exists? :wechat_news_reply_items
    drop_table :wechat_notices if table_exists? :wechat_notices
    drop_table :wechat_partners if table_exists? :wechat_partners
    drop_table :wechat_payee_apps if table_exists? :wechat_payee_apps
    drop_table :wechat_payee_domains if table_exists? :wechat_payee_domains
    drop_table :wechat_payees if table_exists? :wechat_payees
    drop_table :wechat_platform_templates if table_exists? :wechat_platform_templates
    drop_table :wechat_platform_tickets if table_exists? :wechat_platform_tickets
    drop_table :wechat_platforms if table_exists? :wechat_platforms
    drop_table :wechat_provider_organs if table_exists? :wechat_provider_organs
    drop_table :wechat_providers if table_exists? :wechat_providers
    drop_table :wechat_qy_medias if table_exists? :wechat_qy_medias
    drop_table :wechat_receivers if table_exists? :wechat_receivers
    drop_table :wechat_registers if table_exists? :wechat_registers
    drop_table :wechat_replies if table_exists? :wechat_replies
    drop_table :wechat_request_responses if table_exists? :wechat_request_responses
    drop_table :wechat_requests if table_exists? :wechat_requests
    drop_table :wechat_responses if table_exists? :wechat_responses
    drop_table :wechat_scenes if table_exists? :wechat_scenes
    drop_table :wechat_services if table_exists? :wechat_services
    drop_table :wechat_suite_receives if table_exists? :wechat_suite_receives
    drop_table :wechat_suites if table_exists? :wechat_suites
    drop_table :wechat_supporters if table_exists? :wechat_supporters
    drop_table :wechat_tags if table_exists? :wechat_tags
    drop_table :wechat_template_configs if table_exists? :wechat_template_configs
    drop_table :wechat_template_key_words if table_exists? :wechat_template_key_words
    drop_table :wechat_templates if table_exists? :wechat_templates
    drop_table :wechat_user_tags if table_exists? :wechat_user_tags
    drop_table :solid_queue_job_counter_caches if table_exists? :solid_queue_job_counter_caches
    drop_table :statis_counter_years if table_exists? :statis_counter_years
    drop_table :statis_counter_months if table_exists? :statis_counter_months
    drop_table :statis_counter_days if table_exists? :statis_counter_days
    drop_table :datum_errs if table_exists? :datum_errs
    drop_table :mqtt_acl if table_exists? :mqtt_acl
    drop_table :print_tasks if table_exists? :print_tasks
    drop_table :factory_product_provides if table_exists? :factory_product_provides
    drop_table :factory_provides if table_exists? :factory_provides
    drop_table :trade_payment_counter_caches if table_exists? :trade_payment_counter_caches
    drop_table :trade_wallet_prepayments if table_exists? :trade_wallet_prepayments
    drop_table :mqtt_user if table_exists? :mqtt_user
    drop_table :trade_wallet_logs if table_exists? :trade_wallet_logs
    drop_table :trade_wallet_goods if table_exists? :trade_wallet_goods
    drop_table :print_mqtt_printers if table_exists? :print_mqtt_printers
    drop_table :trade_wallet_advances if table_exists? :trade_wallet_advances
    drop_table :trade_order_counter_caches if table_exists? :trade_order_counter_caches
    drop_table :trade_item_counter_caches if table_exists? :trade_item_counter_caches
    drop_table :trade_wallet_templates if table_exists? :trade_wallet_templates
    drop_table :trade_wallets if table_exists? :trade_wallets
    drop_table :ship_packageds if table_exists? :ship_packageds
    drop_table :ship_packages if table_exists? :ship_packages
    drop_table :trade_payment_orders if table_exists? :trade_payment_orders
    drop_table :eventual_place_plans if table_exists? :eventual_place_plans
    drop_table :eventual_apps if table_exists? :eventual_apps
    drop_table :eventual_plan_joins if table_exists? :eventual_plan_joins
  end

end
